// Code generated by vortex. DO NOT EDIT.
// versions:
// 	vortex v0.6.0
// source: api.go

package status

import (
	"context"
	"sync"

	pb "github.com/lemon4ksan/g-man/pkg/protobuf/steam"
	"github.com/lemon4ksan/g-man/pkg/steam/module"
	"github.com/lemon4ksan/g-man/pkg/steam/protocol/enums"
	"google.golang.org/protobuf/proto"
)

type eventsClient struct {
	transport module.InitContext
	mu        sync.Mutex
	unregs    []func()
}

// NewEvents creates a new Events client instance backed by a transport.
func NewEvents(transport module.InitContext) Events {
	return &eventsClient{
		transport: transport,
	}
}

// MustNewEvents initializes Events.
func MustNewEvents(transport module.InitContext) Events {
	return NewEvents(transport)
}

func (c *eventsClient) SendGamesPlayed(ctx context.Context, req *pb.CMsgClientGamesPlayed) error {
	payloadBytes, err := proto.Marshal(req)
	if err != nil {
		return err
	}

	return c.transport.Notify(ctx, enums.EMsg_ClientGamesPlayedWithDataBlob, payloadBytes)
}

// Close unsubscribes all active event listeners.
func (c *eventsClient) Close() error {
	c.mu.Lock()
	for _, unreg := range c.unregs {
		unreg()
	}
	c.unregs = nil
	c.mu.Unlock()
	return nil
}
