// Code generated by vortex. DO NOT EDIT.
// versions:
// 	vortex v0.6.0
// source: api.go

package inventory

import (
	"context"
	"errors"
	"io"
	"net/http"
	"net/url"
	"strconv"

	"github.com/lemon4ksan/g-man/pkg/steam/community"
	"github.com/lemon4ksan/g-man/pkg/steam/id"

	"github.com/lemon4ksan/aoni"
	"github.com/lemon4ksan/aoni/mod"
	"github.com/lemon4ksan/aoni/option"
)

type apiClient struct {
	r *aoni.Client
}

// NewAPI creates a new API client instance backed by an authenticated community.Requester.
func NewAPI(client community.Requester, opts ...aoni.ClientOption) (API, error) {
	if client == nil {
		return nil, errors.New("aoni: client (community.Requester) is required to initialize API")
	}

	var baseOpts []aoni.ClientOption
	baseOpts = append(baseOpts, option.WithHeader("Origin", "https://steamcommunity.com"))
	baseOpts = append(baseOpts, opts...)

	targetReq := aoni.NewClient(client, append([]aoni.ClientOption{option.WithBaseURL("https://steamcommunity.com/")}, baseOpts...)...)

	return &apiClient{
		r: targetReq,
	}, nil
}

// MustNewAPI initializes API and panics if an error occurs.
func MustNewAPI(client community.Requester, opts ...aoni.ClientOption) API {
	api, err := NewAPI(client, opts...)
	if err != nil {
		panic(err)
	}
	return api
}

// R returns the underlying *aoni.Client used by the client.
func (c *apiClient) R() *aoni.Client {
	return c.r
}

func (c *apiClient) GetInventoryPage(ctx context.Context, steamID uint64, appID uint32, contextID int64, req GetInventoryPageRequest, mods ...aoni.RequestModifier) (*inventoryResponse, error) {
	var stackMods [8]aoni.RequestModifier
	allMods := stackMods[:0]

	var refBuf [128]byte
	ref := refBuf[:0]
	ref = append(ref, "https://steamcommunity.com/profiles/"...)
	ref = strconv.AppendUint(ref, uint64(steamID), 10)
	ref = append(ref, "/inventory"...)
	allMods = append(allMods, mod.WithHeader("Referer", string(ref)))

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = req.AppendQuery(qBytes)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	allMods = append(allMods, mod.WithVar("steamID", steamID))
	allMods = append(allMods, mod.WithVar("appID", appID))
	allMods = append(allMods, mod.WithVar("contextID", contextID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.Get[inventoryResponse](ctx, "inventory/{steamID}/{appID}/{contextID}", allMods...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *apiClient) GetInventoryHTML(ctx context.Context, userID uint64, mods ...aoni.RequestModifier) ([]byte, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	allMods = append(allMods, mod.WithVar("userID", userID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.Request(ctx, http.MethodGet, "profiles/{userID}/inventory", allMods...)
	if err != nil {
		return nil, err
	}
	defer aoni.CloseResponse(resp)
	return io.ReadAll(resp.Body)
}

func (c *apiClient) GetInventoryHistoryHTML(ctx context.Context, steamID id.ID, req InventoryHistoryParams, mods ...aoni.RequestModifier) ([]byte, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = req.AppendQuery(qBytes)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	allMods = append(allMods, mod.WithVar("steamID", steamID))
	if len(mods) > 0 {
		allMods = append(allMods, mods...)
	}

	resp, err := c.r.Request(ctx, http.MethodGet, "profiles/{steamID}/inventoryhistory", allMods...)
	if err != nil {
		return nil, err
	}
	defer aoni.CloseResponse(resp)
	return io.ReadAll(resp.Body)
}

func (r *GetInventoryPageRequest) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Language != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "l="...)
		dst = append(dst, url.QueryEscape(r.Language)...)
	}
	if r.Count != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "count="...)
		dst = strconv.AppendInt(dst, int64(r.Count), 10)
	}
	if r.StartAssetID != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "start_assetid="...)
		dst = append(dst, url.QueryEscape(r.StartAssetID)...)
	}

	return dst
}

func (r *GetInventoryPageRequest) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

func (r *GetInventoryPageRequest) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Language != "" {
		vals.Set("l", r.Language)
	}
	if r.Count != 0 {
		vals.Set("count", strconv.FormatInt(int64(r.Count), 10))
	}
	if r.StartAssetID != "" {
		vals.Set("start_assetid", r.StartAssetID)
	}
}

func (r *InventoryHistoryParams) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.Language != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "l="...)
		dst = append(dst, url.QueryEscape(r.Language)...)
	}
	if r.AfterTime != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "after_time="...)
		dst = strconv.AppendInt(dst, int64(r.AfterTime), 10)
	}
	if r.AfterTrade != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "after_trade="...)
		dst = strconv.AppendUint(dst, uint64(r.AfterTrade), 10)
	}
	if r.Direction != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "prev="...)
		dst = strconv.AppendInt(dst, int64(r.Direction), 10)
	}

	return dst
}

func (r *InventoryHistoryParams) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

func (r *InventoryHistoryParams) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.Language != "" {
		vals.Set("l", r.Language)
	}
	if r.AfterTime != 0 {
		vals.Set("after_time", strconv.FormatInt(int64(r.AfterTime), 10))
	}
	if r.AfterTrade != 0 {
		vals.Set("after_trade", strconv.FormatUint(uint64(r.AfterTrade), 10))
	}
	if r.Direction != 0 {
		vals.Set("prev", strconv.FormatInt(int64(r.Direction), 10))
	}
}
