// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package webapi contains strictly typed wrappers for the Steam Web API,
// generated from the GetSupportedAPIList schema.
//
// These functions use service.Doer to execute requests, allowing them
// to be routed via HTTP or Socket depending on the client state.
//
// DO NOT EDIT: All files in this package are generated by cmd/generator/webapi.
//
// Example:
//
//	req := &webapi.ISteamUser_GetPlayerSummaries_v2_Request{Steamids: "7656119..."}
//	res, err := webapi.ISteamUser_GetPlayerSummaries_v2[MyResp](ctx, client, req)
package webapi
