// Code generated by vortex. DO NOT EDIT.
// versions:
// 	vortex v0.6.0
// source: api.go

package directory

import (
	"context"
	"errors"
	"net/url"
	"strconv"

	"github.com/lemon4ksan/g-man/pkg/steam/service"

	"github.com/lemon4ksan/aoni"
	"github.com/lemon4ksan/aoni/mod"
	"github.com/lemon4ksan/aoni/option"
	"github.com/lemon4ksan/aoni/request"
)

type apiClient struct {
	r request.Requester
}

// NewAPI creates a new API client instance backed by an authenticated service.Doer.
func NewAPI(client service.Doer, opts ...aoni.ClientOption) (API, error) {
	if client == nil {
		return nil, errors.New("aoni: client (service.Doer) is required to initialize API")
	}

	var baseOpts []aoni.ClientOption
	baseOpts = append(baseOpts, opts...)

	if req, ok := any(client).(request.Requester); ok && len(opts) == 0 {
		return &apiClient{
			r: req,
		}, nil
	}

	var targetReq request.Requester
	if d, ok := any(client).(aoni.RequestDoer); ok {
		targetReq = request.AsRequester(aoni.Configure(d, append([]aoni.ClientOption{option.WithBaseURL("https://api.steampowered.com/ISteamDirectory")}, baseOpts...)...))
	} else if req, ok := any(client).(request.Requester); ok {
		targetReq = req
	} else if rd, ok := any(client).(interface{ Rest() request.Requester }); ok && rd.Rest() != nil {
		targetReq = rd.Rest()
	} else if rd, ok := any(client).(interface{ Requester() request.Requester }); ok && rd.Requester() != nil {
		targetReq = rd.Requester()
	} else {
		return nil, errors.New("aoni: unsupported requester interface")
	}

	return &apiClient{
		r: targetReq,
	}, nil
}

// MustNewAPI initializes API and panics if an error occurs.
func MustNewAPI(client service.Doer, opts ...aoni.ClientOption) API {
	api, err := NewAPI(client, opts...)
	if err != nil {
		panic(err)
	}
	return api
}

// R returns the underlying request.Requester used by the client.
func (c *apiClient) R() request.Requester {
	return c.r
}

func (c *apiClient) GetCMList(ctx context.Context, req *CMListRequest) (*CMListResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = req.AppendQuery(qBytes)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	type envelope struct {
		Success  bool            `json:"success"`
		Response *CMListResponse `json:"response"`
		ErrorMsg string          `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "GetCMList/v1/", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Response, nil
}

func (c *apiClient) GetCMListForConnect(ctx context.Context, req *CMListForConnectRequest) (*CMListForConnectResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	var qBuf [64]byte
	qBytes := qBuf[:0]
	qBytes = req.AppendQuery(qBytes)
	allMods = append(allMods, mod.WithQuery(string(qBytes)))

	type envelope struct {
		Success  bool                      `json:"success"`
		Response *CMListForConnectResponse `json:"response"`
		ErrorMsg string                    `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "GetCMListForConnect/v1/", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Response, nil
}

func (c *apiClient) GetSteamPipeDomains(ctx context.Context) (*SteamPipeDomainsResponse, error) {
	var stackMods [4]aoni.RequestModifier
	allMods := stackMods[:0]

	type envelope struct {
		Success  bool                      `json:"success"`
		Response *SteamPipeDomainsResponse `json:"response"`
		ErrorMsg string                    `json:"error,omitempty"`
	}

	resp, err := request.GetTo[envelope](ctx, c.r, "GetSteamPipeDomains/v1/", allMods...)
	if err != nil {
		return nil, err
	}
	if !resp.Success && resp.ErrorMsg != "" {
		return nil, errors.New(resp.ErrorMsg)
	}
	return resp.Response, nil
}

func (r *CMListRequest) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.CellID != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "cellid="...)
		dst = strconv.AppendUint(dst, uint64(r.CellID), 10)
	}
	if r.MaxCount != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "maxcount="...)
		dst = strconv.AppendUint(dst, uint64(r.MaxCount), 10)
	}

	return dst
}

func (r *CMListRequest) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

func (r *CMListRequest) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.CellID != 0 {
		vals.Set("cellid", strconv.FormatUint(uint64(r.CellID), 10))
	}
	if r.MaxCount != 0 {
		vals.Set("maxcount", strconv.FormatUint(uint64(r.MaxCount), 10))
	}
}

func (r *CMListForConnectRequest) AppendFormData(dst []byte) []byte {
	if r == nil {
		return dst
	}

	if r.CellID != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "cellid="...)
		dst = strconv.AppendUint(dst, uint64(r.CellID), 10)
	}
	if r.MaxCount != 0 {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "maxcount="...)
		dst = strconv.AppendUint(dst, uint64(r.MaxCount), 10)
	}
	if r.CMType != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "cmtype="...)
		dst = append(dst, url.QueryEscape(r.CMType)...)
	}
	if r.Realm != "" {
		if len(dst) > 0 {
			dst = append(dst, '&')
		}
		dst = append(dst, "realm="...)
		dst = append(dst, url.QueryEscape(r.Realm)...)
	}

	return dst
}

func (r *CMListForConnectRequest) AppendQuery(dst []byte) []byte {
	return r.AppendFormData(dst)
}

func (r *CMListForConnectRequest) EncodeValues(vals url.Values) {
	if r == nil {
		return
	}
	if r.CellID != 0 {
		vals.Set("cellid", strconv.FormatUint(uint64(r.CellID), 10))
	}
	if r.MaxCount != 0 {
		vals.Set("maxcount", strconv.FormatUint(uint64(r.MaxCount), 10))
	}
	if r.CMType != "" {
		vals.Set("cmtype", r.CMType)
	}
	if r.Realm != "" {
		vals.Set("realm", r.Realm)
	}
}
