// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"bytes"
	"encoding/json"
	"log"
	"os"
	"strings"
	"text/template"
)

type APIListResp struct {
	APIList struct {
		Interfaces []Interface `json:"interfaces"`
	} `json:"apilist"`
}

type Interface struct {
	Name    string   `json:"name"`
	Methods []Method `json:"methods"`
}

type Method struct {
	Name        string      `json:"name"`
	Version     int         `json:"version"`
	HTTPMethod  string      `json:"httpmethod"`
	Description string      `json:"description,omitempty"`
	Parameters  []Parameter `json:"parameters,omitempty"`
}

type Parameter struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Optional    bool   `json:"optional"`
	Description string `json:"description,omitempty"`
}

const fileTemplate = `// Code generated by gen tool. DO NOT EDIT.
package webapi

import (
	"context"

	"github.com/lemon4ksan/g-man/pkg/steam/service"
)

{{range .}}
// ============================================================================
// Interface: {{.Name}}
// ============================================================================

{{$ifaceName := .Name}}
{{range .Methods}}
{{$funcName := printf "%s_%s_v%d" $ifaceName .Name .Version}}
{{$reqStruct := printf "%s_Request" $funcName}}

{{if .Description}}// {{$reqStruct}} represents the request parameters for {{.Name}}.
// {{.Description}}{{else}}// {{$reqStruct}} represents the request parameters for {{.Name}}.{{end}}
type {{$reqStruct}} struct {
{{range .Parameters}}	{{if .Description}}// {{.Description}}
{{end}}	{{goName .Name}} {{goType .Type}} ` + "`" + `url:"{{.Name}}{{if .Optional}},omitempty{{end}}"` + "`" + `
{{end}}}

// {{$funcName}} calls {{.Name}} (version {{.Version}}).
{{if .Description}}// {{.Description}}{{end}}
func {{$funcName}}[Resp any](ctx context.Context, d service.Doer, req *{{$reqStruct}}) (*Resp, error) {
	return service.WebAPI[Resp](ctx, d, "{{.HTTPMethod}}", "{{$ifaceName}}", "{{.Name}}", {{.Version}}, req)
}
{{end}}
{{end}}
`

func main() {
	if len(os.Args) < 3 {
		log.Fatalf("Usage: %s <input_json_file> <output_go_file>", os.Args[0])
	}

	inputFile := os.Args[1]
	outputFile := os.Args[2]

	data, err := os.ReadFile(inputFile)
	if err != nil {
		log.Fatalf("Failed to read input file: %v", err)
	}

	var resp APIListResp
	if err := json.Unmarshal(data, &resp); err != nil {
		log.Fatalf("Failed to unmarshal JSON: %v", err)
	}

	funcMap := template.FuncMap{
		"goName": formatGoName,
		"goType": formatGoType,
	}

	tmpl, err := template.New("webapi").Funcs(funcMap).Parse(fileTemplate)
	if err != nil {
		log.Fatalf("Failed to parse template: %v", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, resp.APIList.Interfaces); err != nil {
		log.Fatalf("Failed to execute template: %v", err)
	}

	if err := os.WriteFile(outputFile, buf.Bytes(), 0644); err != nil {
		log.Fatalf("Failed to write output file: %v", err)
	}

	log.Printf("Successfully generated %d interfaces to %s\n", len(resp.APIList.Interfaces), outputFile)
}

func formatGoName(name string) string {
	name = strings.ReplaceAll(name, "[0]", "")

	parts := strings.Split(name, "_")
	for i, part := range parts {
		lower := strings.ToLower(part)
		switch lower {
		case "id":
			parts[i] = "ID"
		case "ip":
			parts[i] = "IP"
		case "steamid":
			parts[i] = "SteamID"
		case "appid":
			parts[i] = "AppID"
		case "url":
			parts[i] = "URL"
		default:
			if len(part) > 0 {
				// Capitalize first letter
				parts[i] = strings.ToUpper(part[:1]) + part[1:]
			}
		}
	}
	return strings.Join(parts, "")
}

func formatGoType(t string) string {
	switch t {
	case "uint64", "uint32", "int32", "bool", "string":
		return t
	case "{message}":
		return "string"
	case "{enum}":
		return "int32"
	case "rawbyte":
		return "[]byte"
	default:
		return "string" // Fallback
	}
}
