// Copyright (c) 2026 Lemon4ksan All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	json "github.com/goccy/go-json"
)

type APIListResp struct {
	APIList struct {
		Interfaces []Interface `json:"interfaces"`
	} `json:"apilist"`
}

type Interface struct {
	Name    string   `json:"name"`
	Methods []Method `json:"methods"`
}

type Method struct {
	Name        string      `json:"name"`
	Version     int         `json:"version"`
	HTTPMethod  string      `json:"httpmethod"`
	Description string      `json:"description,omitempty"`
	Parameters  []Parameter `json:"parameters,omitempty"`

	GoMethodName string
	ReqStruct    string
}

type Parameter struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Optional    bool   `json:"optional"`
	Description string `json:"description,omitempty"`

	GoFieldName string
	GoFieldType string
}

const fileTemplate = `// Code generated by cmd/generator/webapi. DO NOT EDIT.

//go:generate aoni-gen -file=api.go

package webapi

import (
	"context"
	"encoding/json"

	"github.com/lemon4ksan/aoni/request"
)

var _ = request.Requester(nil)
{{range .}}

// {{.Name}} provides methods for the Steam {{.Name}} WebAPI service.
//
// @aoni:service
// @base_url "https://api.steampowered.com/{{.Name}}"
// @requester "request.Requester"
type {{.Name}} interface {
{{- range .Methods}}
{{- if .Description}}
	// {{.GoMethodName}}: {{.Description}}
{{- else}}
	// {{.GoMethodName}} calls /{{.Name}}/v{{.Version}}/.
{{- end}}
	//
{{- if eq .HTTPMethod "POST"}}
	// @post /{{.Name}}/v{{.Version}}/
	// @form
{{- else}}
	// @get /{{.Name}}/v{{.Version}}/
{{- end}}
	{{.GoMethodName}}(ctx context.Context{{if .Parameters}}, req *{{.ReqStruct}}{{end}}) (*json.RawMessage, error)
{{end}}
}
{{range .Methods}}
{{- if .Parameters}}
// {{.ReqStruct}} represents request parameters for {{.GoMethodName}}.
//
// @aoni:dto
type {{.ReqStruct}} struct {
{{- range .Parameters}}
{{- if .Description}}
	// {{.Description}}
{{- end}}
	{{.GoFieldName}} {{.GoFieldType}} ` + "`" + `url:"{{.Name}}{{if .Optional}},omitempty{{end}}"` + "`" + `
{{- end}}
}
{{end}}
{{- end}}
{{end}}
`

func main() {
	inFlag := flag.String("in", "cmd/generator/api.steampowered.com.json", "Path to input Steam WebAPI JSON schema")
	outFlag := flag.String("out", "pkg/steam/webapi/api.go", "Path to output declarative aoni Go file")
	fetchFlag := flag.Bool("fetch", false, "Fetch latest schema from Valve Steam WebAPI")
	runAoniGen := flag.Bool("run-aoni-gen", true, "Automatically run aoni-gen after creating api.go")

	flag.Parse()

	var (
		data []byte
		err  error
	)

	if *fetchFlag {
		log.Println("Fetching latest Steam WebAPI schema from Valve...")

		url := "https://api.steampowered.com/ISteamWebAPIUtil/GetSupportedAPIList/v1/"

		resp, httpErr := http.Get(url) //nolint:gosec,noctx
		if httpErr != nil {
			log.Fatalf("Failed to fetch WebAPI schema: %v", httpErr)
		}
		defer resp.Body.Close()

		data, err = io.ReadAll(resp.Body)
		if err != nil {
			log.Fatalf("Failed to read HTTP response: %v", err)
		}
	} else {
		inputPath := filepath.Clean(*inFlag)

		data, err = os.ReadFile(inputPath)
		if err != nil {
			log.Fatalf("Failed to read schema file %s: %v", inputPath, err)
		}
	}

	var apiResp APIListResp
	if err := json.Unmarshal(data, &apiResp); err != nil {
		log.Fatalf("Failed to unmarshal JSON schema: %v", err)
	}

	for i := range apiResp.APIList.Interfaces {
		iface := &apiResp.APIList.Interfaces[i]

		methodCounts := make(map[string]int)
		for _, m := range iface.Methods {
			methodCounts[m.Name]++
		}

		for j := range iface.Methods {
			m := &iface.Methods[j]

			baseName := formatGoName(m.Name)
			if methodCounts[m.Name] > 1 {
				m.GoMethodName = fmt.Sprintf("%sV%d", baseName, m.Version)
			} else {
				m.GoMethodName = baseName
			}

			m.ReqStruct = fmt.Sprintf("%s_%s_Request", iface.Name, m.GoMethodName)

			for k := range m.Parameters {
				p := &m.Parameters[k]
				p.GoFieldName = formatGoName(p.Name)
				p.GoFieldType = formatGoType(p.Type)
			}
		}
	}

	tmpl, err := template.New("webapi").Parse(fileTemplate)
	if err != nil {
		log.Fatalf("Failed to parse template: %v", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, apiResp.APIList.Interfaces); err != nil {
		log.Fatalf("Failed to execute template: %v", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("Warning: failed to gofmt generated code: %v", err)

		formatted = buf.Bytes()
	}

	outPath := filepath.Clean(*outFlag)
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		log.Fatalf("Failed to create target directory: %v", err)
	}

	if err := os.WriteFile(outPath, formatted, 0o644); err != nil {
		log.Fatalf("Failed to write output file %s: %v", outPath, err)
	}

	log.Printf("Successfully generated declarative aoni DSL for %d interfaces to %s\n",
		len(apiResp.APIList.Interfaces), outPath)

	if *runAoniGen {
		log.Printf("Running aoni-gen on %s...\n", outPath)
		cmd := exec.Command("vortex", "-file="+filepath.Base(outPath))
		cmd.Dir = filepath.Dir(outPath)
		cmd.Stdout = os.Stdout

		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			log.Fatalf("aoni-gen failed: %v", err)
		}

		log.Println("✔ WebAPI compilation completed successfully!")
	}
}

func formatGoName(name string) string {
	name = strings.ReplaceAll(name, "[0]", "")
	name = strings.ReplaceAll(name, "[", "")
	name = strings.ReplaceAll(name, "]", "")

	switch strings.ToLower(name) {
	case "steamid":
		return "SteamID"
	case "steamidkey":
		return "SteamIDKey"
	case "appid":
		return "AppID"
	case "cellid":
		return "CellID"
	case "maxcount":
		return "MaxCount"
	case "cmtype":
		return "CMType"
	case "accountid":
		return "AccountID"
	case "gameid":
		return "GameID"
	case "matchid":
		return "MatchID"
	case "leagueid":
		return "LeagueID"
	case "serverid":
		return "ServerID"
	case "itemid":
		return "ItemID"
	case "classid":
		return "ClassID"
	case "instanceid":
		return "InstanceID"
	case "groupid":
		return "GroupID"
	case "eventid":
		return "EventID"
	case "badgeid":
		return "BadgeID"
	case "sessionid":
		return "SessionID"
	case "clientid":
		return "ClientID"
	case "ugcid":
		return "UGCID"
	case "pickid":
		return "PickID"
	}

	parts := strings.Split(name, "_")
	for i, part := range parts {
		lower := strings.ToLower(part)
		switch lower {
		case "id":
			parts[i] = "ID"
		case "ip":
			parts[i] = "IP"
		case "steamid":
			parts[i] = "SteamID"
		case "appid":
			parts[i] = "AppID"
		case "cellid":
			parts[i] = "CellID"
		case "maxcount":
			parts[i] = "MaxCount"
		case "accountid":
			parts[i] = "AccountID"
		case "url":
			parts[i] = "URL"
		case "rsa":
			parts[i] = "RSA"
		case "rtmp":
			parts[i] = "RTMP"
		case "ugc":
			parts[i] = "UGC"
		case "cidr":
			parts[i] = "CIDR"
		case "asn":
			parts[i] = "ASN"
		case "cdn":
			parts[i] = "CDN"
		case "sdr":
			parts[i] = "SDR"
		case "cm":
			parts[i] = "CM"
		case "dpc":
			parts[i] = "DPC"
		case "csgo":
			parts[i] = "CSGO"
		case "dota2":
			parts[i] = "DOTA2"
		case "tf2":
			parts[i] = "TF2"
		default:
			if len(part) > 0 {
				parts[i] = strings.ToUpper(part[:1]) + part[1:]
			}
		}
	}

	res := strings.Join(parts, "")
	if len(res) == 0 {
		return "Field"
	}

	if res[0] >= '0' && res[0] <= '9' {
		res = "V" + res
	}

	return res
}

func formatGoType(t string) string {
	switch t {
	case "uint64", "uint32", "int32", "bool", "string":
		return t
	case "{message}":
		return "string"
	case "{enum}":
		return "int32"
	case "rawbyte":
		return "[]byte"
	default:
		return "string"
	}
}
